### ISSUE TITLE
ローカルライブラリとしてインストールする際にエラーが発生する

### ISSUE THREAD

**Issue by silverag-corgi** [silverag-corgi/python-lib-for-me#1]
```command
C:\Git\python\twitter-lib-for-me>pipenv install -e "../python-lib-for-me"
Installing -e ../python-lib-for-me...
Error:  An error occurred while installing -e ../python-lib-for-me!
Error text: Obtaining file:///C:/Git/python/python-lib-for-me (from -r c:\users\silverag\appdata\local\temp\pipenv-qz3h__ry-requirements\pipenv-qwtz_j8z-requirement.txt (line 1))
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: 'C:\Git\python\twitter-lib-for-me\.venv\Scripts\python.exe'
            'C:\Git\python\twitter-lib-for-me\.venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py'
            get_requires_for_build_wheel
            'C:\Users\silverag\AppData\Local\Temp\tmp8hu1ytdf'
       cwd: C:\Git\python\python-lib-for-me
  Complete output (22 lines):
  Traceback (most recent call last):
    File "C:\Git\python\twitter-lib-for-me\.venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "C:\Git\python\twitter-lib-for-me\.venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Git\python\twitter-lib-for-me\.venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\silverag\AppData\Local\Temp\pip-build-env-12xk3365\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\silverag\AppData\Local\Temp\pip-build-env-12xk3365\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in _get_build_requires
      self.run_setup()
    File "C:\Users\silverag\AppData\Local\Temp\pip-build-env-12xk3365\overlay\Lib\site-packages\setuptools\build_meta.py", line 266, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\silverag\AppData\Local\Temp\pip-build-env-12xk3365\overlay\Lib\site-packages\setuptools\build_meta.py", line 157, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 2, in <module>
      import python_lib_for_me
    File "C:\Git\python\python-lib-for-me\python_lib_for_me\__init__.py", line 1, in <module>
      from python_lib_for_me.date import *
    File "C:\Git\python\python-lib-for-me\python_lib_for_me\date.py", line 8, in <module>
      from dateutil.relativedelta import relativedelta
  ModuleNotFoundError: No module named 'dateutil'
  ----------------------------------------
WARNING: Discarding file:///C:/Git/python/python-lib-for-me
ERROR: Command errored out with exit status 1

Installation Failed


C:\Git\python\twitter-lib-for-me>ver

Microsoft Windows [Version 10.0.19043.1466]


C:\Git\python\twitter-lib-for-me>pip show pipenv
Name: pipenv
Version: 2022.1.8


C:\Git\python\twitter-lib-for-me>pipenv run py --version
Python 3.10.1


C:\Git\python\twitter-lib-for-me>pipenv run pip list
Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.11
idna               3.3
oauthlib           3.2.0
pip                21.3.1
requests           2.27.1
requests-oauthlib  1.3.1
setuptools         60.5.0
tweepy             4.4.0
urllib3            1.26.8
wheel              0.37.1
```

**Comment by silverag-corgi** [comment]
ローカルのライブラリをアプリケーションに初めてインストールする場合は問題ない。
しかし、別のアプリケーションでインストールする際に、
ライブラリフォルダ配下に自動生成される`pyproject.toml`が上記エラーを発生させている可能性が高い。
そのため、このファイルを事前に削除するか、自動生成されないように設定する必要がある。

また、ライブラリの`setup.py`で`install_requires`を設定しているが、動作していない可能性がある。
そのため、改めて依存関係にあるライブラリを事前にインストールする必要がある。

```command
C:\Git\python\twitter-lib-for-me>pipenv install python-dateutil
Installing python-dateutil...
Adding python-dateutil to Pipfiles [packages]...
Installation Succeeded
Pipfile.lock (7e9846) out of date, updating to (f06cea)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
           Building requirements...
Resolving dependencies...
Success!
Updated Pipfile.lock (f06cea)!
Installing dependencies from Pipfile.lock (f06cea)...
  ================================ 0/0 - 00:00:00
To activate this projects virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.


C:\Git\python\twitter-lib-for-me>pipenv install -e "../python-lib-for-me"
Installing -e ../python-lib-for-me...
Adding python-lib-for-me to Pipfiles [packages]...
Installation Succeeded
Pipfile.lock (09f99f) out of date, updating to (0d5fa6)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
           Building requirements...
Resolving dependencies...
Success!
Updated Pipfile.lock (0d5fa6)!
Installing dependencies from Pipfile.lock (0d5fa6)...
INFO:pep517.envbuild:Temporary build environment: C:\Users\silverag\AppData\Local\Temp\pep517-build-env-yqyoe9i6
INFO:pep517.envbuild:Temporary build environment: C:\Users\silverag\AppData\Local\Temp\pep517-build-env-6tg690n5
  ================================ 0/0 - 00:00:00
To activate this projects virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

**Comment by silverag-corgi** [comment]
コミット 892498b で修正した。

予想になるが、自動生成された`pyproject.toml`が`setup.py`で引数として設定していた情報を上書きしている可能性がある。
そのため、`pyproject.toml`は事前に作成しておき、`setup.py`で設定していた情報を`setup.cfg`に移動した。

**Comment by silverag-corgi** [comment]
コミット 2005987 で再度修正した。

依存関係にあるライブラリがインストールされなかったため、バージョン指定時の空白文字を削除した。
